apiVersion: v1
kind: Service
metadata:
  name: calculator-app-service
spec:
  selector:
    app: calculator-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
  type: LoadBalancer  # If using a cloud provider, otherwise use ClusterIP

